version: 0.0
os: linux
files:
  - source: /wordpress/
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: wordpress/scripts/install_dependencies.sh
      timeout: 300
      runas: root
