version: 0.2

phases:
  build:
    commands:
      - cd wordpress 
      - cat .env.private.enc | ./bin/decrypt.sh > .env
      - if [ ! -s .env ]; then return 1; fi

artifacts:
  files:
    - "**/*"
