---
- name: "Provision Image"
  hosts: all
  become: true

  tasks:
    - name: install php7.4
      command: amazon-linux-extras install -y php7.4
    - name: install httpd
      package:
        name:
          - httpd
          - php-xml
          - ruby
          - mariadb
        state: present
    - name: enable httpd
      systemd:
        name: httpd.service
        enabled: true
    - name: copy httpd config
      copy:
        src: ./files/vhosts.conf
        dest: /etc/httpd/conf.d/vhosts.conf
    - name: copy php config
      copy:
        src: ./files/php.ini
        dest: /etc/php.ini

    - name: install CodeDeploy agent
      shell: |
        curl -L -o /tmp/codedeploy-install https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install && \
        chmod +x /tmp/codedeploy-install && \
        /tmp/codedeploy-install auto
