---
- name: "Provision Image"
  hosts: all
  become: true

  tasks:
    - name: install php7.4
      command: amazon-linux-extras install -y php7.4
    - name: install httpd
      package:
        name:
          - httpd
          - php-xml
          - ruby
        state: present
    - name: enable httpd
      systemd:
        name: httpd.service
        enabled: true
    - name: install composer
      get_url:
        url: https://getcomposer.org/download/latest-stable/composer.phar
        dest: /usr/local/bin/composer
        mode: 775
    - name: copy httpd config
      copy:
        src: ./files/vhosts.conf
        dest: /etc/httpd/conf.d/vhosts.conf

    - name: install CodeDeploy agent
      shell: |
        curl -L -o /tmp/codedeploy-install https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install && \
        chmod +x /tmp/codedeploy-install && \
        /tmp/codedeploy-install auto
